<script setup>
import { computed, reactive, ref } from 'vue'
const screen = ref('login'), notice = ref(''), error = ref(''), devToken = ref(''), loading = ref(false)
const login = reactive({email:'gerente@taller.local',password:'Gerente123!'})
const register = reactive({name:'',email:'',password:'',confirm:''})
const forgot = reactive({email:''}), reset = reactive({token:'',password:'',confirm:''})
const api = async (url, body, method='POST') => { const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}); const d=await r.json(); if(!r.ok) throw new Error(d.message||'No se pudo completar la operación'); return d }
const clear = () => { notice.value='';error.value='' }
async function submitLogin(){ clear(); loading.value=true; try { const d=await api('/api/auth/login',login); notice.value=`Bienvenido/a, ${d.user.name}. Rol: ${d.user.role}.`; screen.value='welcome' } catch(e){error.value=e.message} finally{loading.value=false} }
async function submitRegister(){ clear(); if(register.password!==register.confirm){error.value='Las contraseñas no coinciden.';return}; loading.value=true; try { const d=await api('/api/auth/register',register);notice.value=d.message;screen.value='login'} catch(e){error.value=e.message} finally{loading.value=false} }
async function submitForgot(){ clear(); loading.value=true; try {const d=await api('/api/auth/forgot-password',forgot);notice.value=d.message;devToken.value=d.developmentToken||'';if(devToken.value) reset.token=devToken.value }catch(e){error.value=e.message}finally{loading.value=false} }
async function submitReset(){ clear();if(reset.password!==reset.confirm){error.value='Las contraseñas no coinciden.';return};loading.value=true;try{const d=await api('/api/auth/reset-password',reset);notice.value=d.message;screen.value='login'}catch(e){error.value=e.message}finally{loading.value=false}}
const title = computed(()=>({login:'Inicia sesión',register:'Crea tu cuenta',forgot:'Recupera tu acceso',reset:'Define una contraseña nueva',welcome:'Acceso autorizado'})[screen.value])
</script>
<template>
 <main class="grid min-h-screen lg:grid-cols-2">
  <section class="relative hidden overflow-hidden bg-gradient-to-br from-lilac-700 via-purple-700 to-fuchsia-500 p-14 text-white lg:flex lg:flex-col lg:justify-between">
   <div class="flex items-center gap-3 font-semibold"><span class="grid h-10 w-10 place-items-center rounded-xl bg-white/20 text-xl">⚙</span>Taller Morado</div>
   <div><p class="mb-4 text-sm font-semibold tracking-[.2em] text-lilac-100">GESTIÓN INTELIGENTE</p><h1 class="max-w-lg text-5xl font-bold leading-tight">Tu taller, <span class="text-lilac-300">siempre</span> en movimiento.</h1><p class="mt-6 max-w-md text-lg text-white/75">Órdenes de reparación, clientes y equipo reunidos en un solo lugar.</p></div>
   <p class="text-sm text-white/55">Protegemos la información de tu negocio.</p>
   <div class="absolute -bottom-28 -right-20 h-80 w-80 rounded-full bg-white/10"></div>
  </section>
  <section class="flex items-center justify-center p-6 sm:p-10"><div class="w-full max-w-md">
   <div class="mb-10 lg:hidden flex items-center gap-2 text-lg font-bold text-lilac-700"><span>⚙</span>Taller Morado</div>
   <div class="mb-8"><p class="text-sm font-semibold text-lilac-700">BIENVENIDO</p><h2 class="mt-1 text-3xl font-bold">{{ title }}</h2><p class="mt-2 text-sm text-slate-500" v-if="screen==='register'">Tu cuenta inicia como Cliente; un gerente puede ajustar tu rol después.</p></div>
   <div v-if="notice" class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{{notice}}</div><div v-if="error" class="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{{error}}</div>
   <form v-if="screen==='login'" @submit.prevent="submitLogin" class="space-y-5"><label class="block text-sm font-medium">Correo electrónico<input v-model="login.email" type="email" required class="mt-2" placeholder="nombre@taller.com"></label><label class="block text-sm font-medium">Contraseña<input v-model="login.password" type="password" required class="mt-2" placeholder="••••••••"></label><button type="button" @click="screen='forgot';clear()" class="text-sm font-semibold text-lilac-700 hover:underline">¿Olvidaste tu contraseña?</button><button :disabled="loading" class="w-full rounded-xl bg-lilac-700 py-3 font-semibold text-white shadow-lg shadow-purple-200 hover:bg-purple-800 disabled:opacity-60">{{loading?'Validando…':'Iniciar sesión'}}</button><p class="text-center text-sm text-slate-500">¿Aún no tienes cuenta? <button type="button" @click="screen='register';clear()" class="font-semibold text-lilac-700">Regístrate</button></p></form>
   <form v-else-if="screen==='register'" @submit.prevent="submitRegister" class="space-y-4"><label class="block text-sm font-medium">Nombre completo<input v-model="register.name" required class="mt-1"></label><label class="block text-sm font-medium">Correo electrónico<input v-model="register.email" type="email" required class="mt-1"></label><label class="block text-sm font-medium">Contraseña <span class="font-normal text-slate-400">mínimo 8 caracteres</span><input v-model="register.password" type="password" minlength="8" required class="mt-1"></label><label class="block text-sm font-medium">Confirmar contraseña<input v-model="register.confirm" type="password" required class="mt-1"></label><button :disabled="loading" class="w-full rounded-xl bg-lilac-700 py-3 font-semibold text-white">Crear cuenta</button><button type="button" @click="screen='login';clear()" class="w-full text-sm font-semibold text-lilac-700">Volver a iniciar sesión</button></form>
   <form v-else-if="screen==='forgot'" @submit.prevent="submitForgot" class="space-y-5"><p class="text-sm text-slate-500">Te enviaremos un enlace seguro para restablecer tu contraseña.</p><label class="block text-sm font-medium">Correo electrónico<input v-model="forgot.email" type="email" required class="mt-2"></label><button :disabled="loading" class="w-full rounded-xl bg-lilac-700 py-3 font-semibold text-white">Enviar instrucciones</button><div v-if="devToken" class="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Modo desarrollo — token: <code class="break-all">{{devToken}}</code><button @click="screen='reset'" type="button" class="mt-2 block font-bold underline">Continuar con el token</button></div><button type="button" @click="screen='login';clear()" class="w-full text-sm font-semibold text-lilac-700">Volver</button></form>
   <form v-else-if="screen==='reset'" @submit.prevent="submitReset" class="space-y-4"><label class="block text-sm font-medium">Token de recuperación<input v-model="reset.token" required class="mt-1"></label><label class="block text-sm font-medium">Nueva contraseña<input v-model="reset.password" type="password" minlength="8" required class="mt-1"></label><label class="block text-sm font-medium">Confirmar contraseña<input v-model="reset.confirm" type="password" required class="mt-1"></label><button :disabled="loading" class="w-full rounded-xl bg-lilac-700 py-3 font-semibold text-white">Guardar contraseña</button></form>
   <div v-else class="rounded-2xl border border-lilac-100 bg-white p-6 shadow-sm"><div class="mb-4 text-3xl">✓</div><p class="text-slate-600">La siguiente etapa será el tablero de órdenes de reparación según los permisos de tu rol.</p><button @click="screen='login';clear()" class="mt-6 rounded-xl bg-lilac-700 px-5 py-3 text-sm font-semibold text-white">Cerrar sesión</button></div>
   <p class="mt-10 text-center text-xs text-slate-400">Acceso protegido · Contraseñas cifradas con BCrypt</p>
  </div></section>
 </main>
</template>
