spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/taller?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USER:taller_user}
    password: ${DB_PASSWORD:taller_pass}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB
  error:
    include-message: never
